// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcBJsUuEc8Sj50FKPB3_4T2XmAJ9HcLOE',
    appId: '1:301596451344:web:e0720c634d9fb76670e095',
    messagingSenderId: '301596451344',
    projectId: 'chatterjee-607af',
    authDomain: 'chatterjee-607af.firebaseapp.com',
    storageBucket: 'chatterjee-607af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx3-OAjVfzyTJcjjxvC7Z7AHXrjVELvyg',
    appId: '1:301596451344:android:a02954bebc39d55570e095',
    messagingSenderId: '301596451344',
    projectId: 'chatterjee-607af',
    storageBucket: 'chatterjee-607af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo_aiLV-vvtlrShDuy0HQFfroPqj_61ao',
    appId: '1:301596451344:ios:f1f7e762901e2d3070e095',
    messagingSenderId: '301596451344',
    projectId: 'chatterjee-607af',
    storageBucket: 'chatterjee-607af.firebasestorage.app',
    iosBundleId: 'com.izhar-khan.chatter-jee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo_aiLV-vvtlrShDuy0HQFfroPqj_61ao',
    appId: '1:301596451344:ios:974f8fe8f1af4c7870e095',
    messagingSenderId: '301596451344',
    projectId: 'chatterjee-607af',
    storageBucket: 'chatterjee-607af.firebasestorage.app',
    iosBundleId: 'com.example.chatterJee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcBJsUuEc8Sj50FKPB3_4T2XmAJ9HcLOE',
    appId: '1:301596451344:web:ae43319265e5cb9b70e095',
    messagingSenderId: '301596451344',
    projectId: 'chatterjee-607af',
    authDomain: 'chatterjee-607af.firebaseapp.com',
    storageBucket: 'chatterjee-607af.firebasestorage.app',
  );
}
